name: Blog Posts

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update README.md with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jkkrow/blog-post-workflow@master
        with:
          feed_list: 'https://blog.joonku.net/rss/json'
          accept_header: 'application/json'
          max_post_count: '4'
          date_format: 'mediumDate'
          template: '<table><tr><td width="250"><a href="$url"><img src="$image"></a></td>$newline<td width="400"><a href="$url">$title</a><br/>$date</td></tr></table>$newline'
